root: true
env:
  browser: true
  es2022: true # Vuetify recommended
  node: true
extends:
  - eslint:recommended
  - google
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:vue/recommended
  - plugin:vuejs-accessibility/recommended
  - plugin:vuetify/base
  - '@vue/eslint-config-prettier'
plugins:
  - '@typescript-eslint'
  - vue
parser: vue-eslint-parser
parserOptions:
  ecmaVersion: latest
  parser: '@typescript-eslint/parser'
  sourceType: module
  createDefaultProgram: true
rules:
  new-cap: off
  no-invalid-this: off
  no-unused-vars: off
  no-undef: off
  require-jsdoc: off
  valid-jsdoc: off
  tsdoc/syntax: off
  vue/html-self-closing:
  - error
  - html:
  void: always
  vue/multi-word-component-names: 0
overrides:
  - files:
  - '*.html'
  processor: vue/.vue
settings:
  import/parsers:
    '@typescript-eslint/parser':
    - '*.ts'
    - '*.tsx'
    - '*.vue'
  import/resolver:
    typescript: {}
    alias:
      map:
        - ['@', './src']
        - ['~', './node_modules']
      extensions:
        - .js
        - .ts
        - .jsx
        - .tsx
        - .vue
  vite:
    configPath: ./vite.config.ts